version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
      - ./init_functions.sql:/docker-entrypoint-initdb.d/init_functions.sql
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
