version: '3.1'
services:
  db:
    image: postgres
restart: always
ports:
  - "5432:5432"
volumes:
  - ./init.sql:/docker-entrypoint-initdb.d/init_database.sql
environment:
  - POSTGRES_USER=sammy
  - POSTGRES_PASSWORD=123
  - POSTGRES_DB=postgres
