version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
     - "3306:3306"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
     - server
    environment:
     - MYSQL_USER=test
     - MYSQL_PASSWORD=test
     - MYSQL_DATABASE=testdb
     - MYSQL_ROOT_PASSWORD=testroot
networks:
  server: